export enum Routes {
  NotFound = '*',
  Root = '/',
  Home = '/home',
  // LearnersHome = 'learners-home',
  Learners = '/learners',
  App = '/app',

  SignIn = '/signin',
  Login = '/signin/login',
  Register = '/signin/register',
  SignUpRole = ':role',

  Welcome = "/signin/welcome",
  Verification = '/signin/verification',
  Verify = '/signin/verify',
  ResetPassword = '/signin/reset-password',
  ChangePassword = '/signin/change-password',
  ChangeEmail = '/signin/change-email',

  Learner = '/app/learner',
  LearnerHome = '/app/learner/home',
  LearnerDashboard = '/app/learner/dashboard',
  LearnerChats = '/app/learner/chats',
  LearnerCommunity = '/app/learner/community',
  LearnerProfile = '/app/learner/profile',
  LearnerHelp = '/app/learner/help',

  Expert = '/app/expert',
  ExpertHome = '/app/expert/home',
  ExpertAvatar = '/app/expert/avatar',
  ExpertWisdom = '/app/expert/wisdom',
  ExpertWisdomUpload = '/app/expert/wisdom/upload',
  ExpertWisdomUploadToCollection = '/app/expert/wisdom/upload/:collectionId?',
  ExpertWisdomCreateCollection = '/app/expert/wisdom/create-collection',
  ExpertWisdomFiles = '/app/expert/wisdom/files',
  ExpertWisdomCollections = '/app/expert/wisdom/collections',
  ExpertWisdomCollection = '/app/expert/wisdom/collections/:collectionId',
  ExpertProfile = '/app/expert/profile',
  ExpertProfileBilling = '/app/expert/profile/billing',
  ExpertProfileSettings = '/app/expert/profile/settings',
  ExpertHelp = '/app/expert/help',
}
